# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170110_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
