# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170110_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='md5sum',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage=upload.models.MediaFileSystemStorage(), upload_to=upload.models.media_file_name),
        ),
    ]
