# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20170117_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage=upload.models.MediaFileSystemStorage(), upload_to=upload.models.media_file_name, validators=[upload.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='md5sum',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
