# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20170127_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='NotReady', max_length=36),
            preserve_default=False,
        ),
    ]
